adminpanel/urls.py
from django.urls import path
from . import views


app_name = 'adminpanel'

urlpatterns = [
    path('admin_home/', views.admin_home, name='admin_home'),
    path('board_manage/', views.board_manage, name='board_manage'),
    path('delete-boards/', views.delete_boards, name='delete_boards'),
    path('senario/', views.senario, name='senario'),
    path('csv_upload/', views.csv_upload, name='csv_upload'),
    path('delete-senario/', views.delete_senario, name='delete_senario'),
    path('user_list/', views.user_list_view, name='user_list_view'),
    path('user_list/<int:user_no>/', views.user_detail, name='user_detail'),
    path('delete_users/', views.delete_users, name='delete_users'),
    path('notice_manage/', views.notice_manage, name='notice_manage'),
    path('delete-notice-boards/', views.delete_notice_boards, name='delete_notice_boards'),
    path('create_notice/', views.create_notice, name='create_notice'),
    path('notice/<int:pk>/', views.notice_detail, name='notice_detail'),
    path('notice/edit/<int:pk>/', views.edit_notice, name='edit_notice'),
    path('board/<int:pk>/', views.board_detail, name='board_detail'),
    path("control/", views.control_load,name='control'),
    path("home/", views.main_load,name='home'),
    path('notice/<int:pk>/download/', views.generate_presigned_url, name='generate_presigned_url'),


]

control/urls.py
from . import views
from django.urls import path
from .views import send_sms

app_name = 'control'
urlpatterns = [
    path("", views.control_view,name='control'),
    path('send-sms/', send_sms, name='send_sms'),
    path('video_feed/<int:cctv_code>/', views.video_feed, name='video_feed'),
    path('human_status/<str:cctv_code>/', views.human_status, name='human_status'),
    path('stop_stream/', views.stop_stream, name='stop_stream'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.signin, name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("home", views.home, name='home'),
    path("myprofile", views.myprofile, name='myprofile'),
    path("board", views.board, name='board'),
    path("free_board", views.free_board, name='free_board'),
    path("cctv", views.cctv, name='cctv'),
    path("weather", views.control_view, name='weather'),
    path("signup", views.signup,name='signup'),
    path("risk", views.risk,name='risk'),
    path('forgotpw/', views.forgotpw, name='forgotpw'),
    path('adminpanel/', views.admin_panel, name='admin_panel'),
    path('create_freeboard/', views.create_freeboard, name='create_freeboard'),  
    path('myposts/', views.myposts, name='myposts'),
    path('agreement/', views.agreement, name='agreement'),
    path('board/<int:pk>/', views.board_detail, name='board_detail'),
    path('create_freeboard/', views.create_freeboard, name='create_freeboard'),
    path('free_board/<int:pk>/', views.freeboard_detail, name='freeboard_detail'),
    path('freeboard/edit/<int:pk>/', views.edit_freeboard, name='edit_freeboard'),
    path('delete/<int:post_id>/', views.delete_freeboard, name='delete_freeboard'),
    path('team_info', views.team_info, name='team_info'),
    path('load_prediction/', views.load_prediction, name='load_prediction'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('copyright', views.copyright, name='copyright'),
    path("chat/", views.chat, name='chat'),
    path("chat/clear_logs/", views.chat_clear_logs, name='chat_clear_logs'),
    path('auto_admin_login', views.auto_admin_login, name='auto_admin_login'),
    path('get_scenarios/<str:scenario_type>/', views.get_scenarios, name='get_scenarios'),
    path('freeboard/<int:pk>/download/', views.generate_presigned_url, name='generate_presigned_url'),
    path('board/<int:pk>/download/', views.board_generate_presigned_url, name='board_generate_presigned_url'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("control/", include('control.urls')),
    path('adminpanel/', include('adminpanel.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

adminpanel/models.py
from django.db import models

adminpanel/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import json
import csv
import io
import boto3
from django.conf import settings
from collections import Counter
from django.db.models import Q
from django.utils.timezone import localtime
import time 
import hmac
import hashlib
import uuid
import requests
import os
import datetime
from datetime import datetime, timedelta
from datetime import timezone as dt_timezone  
from django.utils import timezone
from .utils import mask_user_data
from urllib.parse import quote

from main.views import add_qa_to_database
from main.forms import *
from main.models import *

def get_signature(key, msg):
    return hmac.new(key.encode(), msg.encode(), hashlib.sha256).hexdigest()

def unique_id():
    return str(uuid.uuid1().hex)

def get_iso_datetime():
    utc_offset_sec = time.altzone if time.localtime().tm_isdst else time.timezone
    utc_offset = timedelta(seconds=-utc_offset_sec)
    return datetime.now().replace(tzinfo=dt_timezone(offset=utc_offset)).isoformat()

def get_headers(apiKey, apiSecret):
    date = get_iso_datetime()
    salt = unique_id()
    data = date + salt
    signature = get_signature(apiSecret, data)
    headers = {
        'Authorization': f'HMAC-SHA256 ApiKey={apiKey}, Date={date}, salt={salt}, signature={signature}',
        'Content-Type': 'application/json'
    }
    return headers

def format_date(date_string):
    if date_string is None:
        return None
    date_obj = datetime.strptime(date_string, '%Y-%m-%dT%H:%M:%S.%fZ').replace(tzinfo=dt_timezone.utc)
    kst = dt_timezone(timedelta(hours=9))
    local_date_obj = date_obj.astimezone(kst)
    return local_date_obj.strftime('%Y-%m-%d %H:%M:%S')

def fetch_message_details(message_code):
    MESSAGE_API_KEY = os.getenv('MESSAGE_API_KEY')
    MESSAGE_API_SECRET = os.getenv('MESSAGE_API_SECRET')

    url = f"http://api.coolsms.co.kr/messages/v4/list?criteria=messageId&value={message_code}&cond=eq"
    headers = get_headers(MESSAGE_API_KEY, MESSAGE_API_SECRET)

    response = requests.get(url, headers=headers)

    response_json = response.json()
    if 'messageList' in response_json and response_json['messageList']:
        message_list = response_json.get('messageList', {})
        extracted_messages = []
        for message_id, message_data in message_list.items():
            text = message_data.get('text')
            from_number = message_data.get('from')
            deliver_date = message_data.get('dateReceived')
            if text and deliver_date:
                extracted_messages.append({
                    'text': text,
                    'from': from_number,
                    'deliver_date': format_date(deliver_date)
                })
            return extracted_messages

    return None

@login_required
def admin_home(request):

    beaches = Beach.objects.all()
    beach_count = Beach.objects.count()
    user_count = User.objects.count()
    board_count = Event_board.objects.count()
    notice_board_count = Notice_board.objects.count()
    
    last_logins = User.objects.values_list('last_login', flat=True)

    login_count = Counter()

    
    for login_time in last_logins:
        local_login_time = localtime(login_time)
        if local_login_time:
            hour = local_login_time.hour
            login_count[hour] +=1
    
    hours = list(range(24))
    counts = [login_count[hour] for hour in hours]
    
    
    message_codes = Message.objects.values_list('message_code', flat=True)
    messages = []
    for message_code in message_codes:
        message_details = fetch_message_details(message_code)
        if isinstance(message_details, list):
            messages.extend(message_details)
        else:
            messages.append(message_details)
    
    sorted_messages = sorted(messages, key=lambda x: x.get('deliver_date', ''), reverse=True)
    return render(request, 'adminpanel/admin_home.html',
                  {'hours':hours, 'counts':counts, 'beaches': beaches, 
                   'user_count':user_count, 'beach_count':beach_count,
                   'board_count':board_count, 'notice_board_count':notice_board_count,
                   'messages':sorted_messages
                   })


@login_required
def senario(request):
    scenario_code = request.GET.get('scenario_code', '')

    if scenario_code:
        scenario_list = Scenario.objects.filter(scenario_code=scenario_code)
    else:
        scenario_list = Scenario.objects.all()

    paginator = Paginator(scenario_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    
    return render(request, 'adminpanel/senario.html', {'page_obj': page_obj, 'scenario_code': scenario_code})



# CSV 업로드 핸들러
@login_required
def csv_upload(request):
    if request.method == 'POST':
        csv_file = request.FILES['csv_file']
        if not csv_file.name.endswith('.csv'):
            return render(request, 'csv_upload.html', {'error': 'CSV 파일이 아닙니다.'})
        
        file_data = csv_file.read().decode('utf-8-sig')
        csv_reader = csv.reader(io.StringIO(file_data))
        next(csv_reader)  # 첫 번째 행(헤더) 건너뛰기
        
        # 현재 마지막 ID 저장
        last_id = Scenario.objects.latest('scenario_id').scenario_id if Scenario.objects.exists() else 0
        
        for row in csv_reader:
            if len(row) < 6:
                continue
            
            try:
                scenario_time = datetime.strptime(row[2], '%H:%M')
            except ValueError:
                continue
            
            Scenario.objects.create(
                scenario_code=row[1],
                scenario_time=scenario_time,
                scenario_situation=row[3],
                scenario_process=row[4],
                scenario_goals=row[5],
                scenario_qa=row[6]
            )
        
        add_qa_to_database(last_id)
        return redirect('adminpanel:senario')
    
    return render(request, 'adminpanel/csv_upload.html')

@login_required
def delete_senario(request):
    try:
        data = json.loads(request.body)
        ids_to_delete = data['ids']
        Scenario.objects.filter(scenario_id__in=ids_to_delete).delete()
        return JsonResponse({"status": "success"}, status=200)
    except Exception as e:
        return JsonResponse({"status": "error", "message": str(e)}, status=400)

# 자유게시판
@login_required
def board_manage(request):    
    beach_no = request.GET.get('beach_no')
    
    if beach_no == 'common':
        posts = Event_board.objects.filter(beach_no__isnull=True).order_by('-event_wdate')
    elif beach_no:
        posts = Event_board.objects.filter(beach_no=beach_no).order_by('-event_wdate')
    else:
        posts = Event_board.objects.all().order_by('-event_wdate')
    
    # 검색 기능
    search_keyword = request.GET.get('q', '')
    search_type  = request.GET.get('type', '')
    
    if search_keyword:
        if len(search_keyword) > 1:
            if search_type == 'all': 
                posts = posts.filter(Q (event_title__icontains=search_keyword) 
                                              | Q (event_contents__icontains=search_keyword) 
                                              | Q (user_no__user_name__icontains=search_keyword) )
            elif search_type =='title':
                posts = posts.filter(event_title__icontains=search_keyword)
                
            elif search_type == 'content' :
                posts = posts.filter(event_contents__icontains=search_keyword)
                
            elif search_type == 'writer' :
                posts = posts.filter(user_no__user_name__icontains=search_keyword)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요!')
    
    # 페이징 처리
    paginator = Paginator(posts, 10) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    beaches = Beach.objects.all()
    
    return render(request, 'adminpanel/board_manage.html', {'posts': posts, 'page_obj': page_obj, 'beaches' : beaches})

@require_POST
@login_required
def delete_boards(request):
    try:
        data = json.loads(request.body)
        ids_to_delete = data['ids']
        Event_board.objects.filter(event_id__in=ids_to_delete).delete()
        return JsonResponse({"status": "success"}, status=200)
    except Exception as e:
        return JsonResponse({"status": "error", "message": str(e)}, status=400)
    
@login_required
def user_list_view(request):
    users = User.objects.all().order_by('user_no') 
    masked_users = [mask_user_data(user) for user in users]
    paginator = Paginator(masked_users, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, 'adminpanel/user_list.html', context)

@login_required
def user_detail(request, user_no):
    user_info = User.objects.get(user_no=user_no)
    return render(request, 'adminpanel/user_detail.html', {'user_info': user_info})

@csrf_exempt
@login_required
def delete_users(request):
    if request.method == 'POST':
        user_ids = request.POST.getlist('ids[]')
        if user_ids:
            User.objects.filter(user_no__in=user_ids).delete()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'no ids provided'}, status=400)
    return JsonResponse({'status': 'invalid request'}, status=400)

# 공지사항
@login_required
def notice_manage(request):
    beach_no = request.GET.get('beach_no')

    
    if beach_no == 'common':
        posts = Notice_board.objects.filter(beach_no__isnull=True).order_by('-notice_wdate')

adminpanel/templates/base/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}제목을 입력하세요{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    {% block extra-style %}
       
    {% endblock %}


</head>

<body>
    <div class="container-fluid position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                {% block sidebar_brand %}
                {% endblock %}
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{% static 'img/face_24dp.png'%}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">27조 <span id="masked-user-name">{{ user.user_name }}</span></h6>
                        <span id="masked-user-id">{{ user.user_id }}</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    
                    <a href="{% url 'adminpanel:admin_home' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'admin_home' %}active{% endif %}"><img class="fa fa-th me-2" src="{% static 'img/home_24dp.png'%}" style="width: 40px; height: 40px;"></i>관리자 홈</a>
                    <a href="{% url 'adminpanel:user_list_view'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'user_list_view' %}active{% endif %}"><img class="fa fa-th me-2" src="{% static 'img/face_24dp.png'%}" style="width: 40px; height: 40px;"></i>사용자 정보 관리</a>
                    <a href="{% url 'adminpanel:senario'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'senario' %}active{% endif %}"><img class="fa fa-th me-2" src="{% static 'img/wysiwyg_24dp.png'%}" style="width: 40px; height: 40px;"></i>훈련시나리오 관리</a>
                    <a href="{% url 'adminpanel:notice_manage'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'notice_manage' %}active{% endif %}"><img class="fa fa-th me-2" src="{% static 'img/chat_24dp.png'%}" style="width: 40px; height: 40px;"></i>공지사항 관리</a>
                    <a href="{% url 'adminpanel:board_manage'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'board_manage' %}active{% endif %}"><img class="fa fa-th me-2" src="{% static 'img/chat_24dp.png'%}" style="width: 40px; height: 40px;"></i>자유게시판 관리</a>
                    
                    
                    
                    
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
           <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="#" class="sidebar-toggler flex-shrink-0"><i class="fa fa-bars"></i></a>
                 
                <a href="{% url 'home' %}"><img src="{% static 'img/logo_choi.png' %}" width="150" height="70" id="main-logo"></i></a>    
                
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" style="border:none; background:none;">로그아웃</button>
                        </form>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="{% url 'home' %}" class="nav-item nav-link">메인 홈</a>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="{% url 'control:control' %}" class="nav-item nav-link">해양 관제 시스템</a>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
        {% block content %}{% endblock %}
    
    <!-- Content End -->
    <!-- Footer Start -->
    <div class="container-fluid pt-4 px-4 sticky-footer">
        <footer class='rounded-top p-4'>
            <div class="footer-content" style="display: flex; justify-content: space-between; align-items: center;">
                <div class="footer-text" style="text-align: left; padding-left: 20px;">
                    <p>
                        <a href="{% url 'team_info' %}">팀 소개</a> |
                        <a href="{% url 'privacy_policy' %}">개인정보처리방침</a> |
                        <a href="{% url 'copyright' %}">저작권보호정책</a>
                    </p>
                    <div class="footer-info" style="line-height: 0.1;">
                        <p>[61251] 7F, 15, Mudeung-ro 202beon-gil, Buk-gu, Gwangju, Republic of Korea.</p>
                        <p>ⓒ2024. Aivle-School 5th BigProject Team27.</p>
                        <p>문의 a055555@aivle.kt.co.kr</p>
                    </div>
                </div>
                <div class="footer-logos" style="text-align: right; padding-right: 20px; display: flex; column-gap: 20px;">
                    <a href="https://corp.kt.com/" target="_blank" style="margin-right: 10px;"><img src="/static/img/kt_logo.png" alt="KT Logo"></a>
                    <a href="https://aivle.kt.co.kr/home/main/indexMain" target="_blank" style="margin-right: 10px;"><img src="/static/img/aivle_logo.png" alt="Aivle Logo"></a>
                    <a href="https://www.instagram.com/reel/C9NQkQDyf9a/?igsh=a3hjMTVzb2kxZjV6" target="_blank"><img src="/static/img/last_logo.png" alt="New Logo"></a>
                </div>
            </div>
        </footer>
            <!-- Footer End -->
        </div>
        <!-- Content End -->
       
    </div>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js'%}"></script>
    
    {% block end-script %} 
    {% endblock %}

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            function maskName(name) {
                if (name.length <= 1) {
                    return name; // 이름이 한 글자일 경우 마스킹하지 않음
                }
                return name[0] + '*' + name.slice(2);
            }
        
            var userNameElement = document.getElementById('masked-user-name');
            if (userNameElement) {
                var maskedName = maskName(userNameElement.textContent.trim());
                userNameElement.textContent = maskedName;
            }
            function maskUserId(userId) {
                if (userId.length <= 2) {
                    return userId; // ID가 2글자 이하일 경우 마스킹하지 않음
                }
                let maskedLength = Math.min(2, userId.length - 2);
                let start = Math.floor((userId.length - maskedLength) / 2);
                return userId.slice(0, start) + '*'.repeat(maskedLength) + userId.slice(start + maskedLength);
            }
            var userIdElement = document.getElementById('masked-user-id');
            if (userIdElement) {
                var maskedId = maskUserId(userIdElement.textContent.trim());
                userIdElement.textContent = maskedId;
            }
        });
    </script>

</body>
</html>