adminpanel/urls.py
from django.urls import path
from . import views


app_name = 'adminpanel'

urlpatterns = [
    path('admin_home/', views.admin_home, name='admin_home'),
    path('board_manage/', views.board_manage, name='board_manage'),
    path('delete-boards/', views.delete_boards, name='delete_boards'),
    path('senario/', views.senario, name='senario'),
    path('csv_upload/', views.csv_upload, name='csv_upload'),
    path('delete-senario/', views.delete_senario, name='delete_senario'),
    path('user_list/', views.user_list_view, name='user_list_view'),
    path('user_list/<int:user_no>/', views.user_detail, name='user_detail'),
    path('delete_users/', views.delete_users, name='delete_users'),
    path('notice_manage/', views.notice_manage, name='notice_manage'),
    path('delete-notice-boards/', views.delete_notice_boards, name='delete_notice_boards'),
    path('create_notice/', views.create_notice, name='create_notice'),
    path('notice/<int:pk>/', views.notice_detail, name='notice_detail'),
    path('notice/edit/<int:pk>/', views.edit_notice, name='edit_notice'),
    path('board/<int:pk>/', views.board_detail, name='board_detail'),
    path("control/", views.control_load,name='control'),
    path("home/", views.main_load,name='home'),
    path('notice/<int:pk>/download/', views.generate_presigned_url, name='generate_presigned_url'),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.signin, name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("home", views.home, name='home'),
    path("myprofile", views.myprofile, name='myprofile'),
    path("board", views.board, name='board'),
    path("free_board", views.free_board, name='free_board'),
    path("cctv", views.cctv, name='cctv'),
    path("weather", views.control_view, name='weather'),
    path("signup", views.signup,name='signup'),
    path("risk", views.risk,name='risk'),
    path('forgotpw/', views.forgotpw, name='forgotpw'),
    path('adminpanel/', views.admin_panel, name='admin_panel'),
    path('create_freeboard/', views.create_freeboard, name='create_freeboard'),  
    path('myposts/', views.myposts, name='myposts'),
    path('agreement/', views.agreement, name='agreement'),
    path('board/<int:pk>/', views.board_detail, name='board_detail'),
    path('create_freeboard/', views.create_freeboard, name='create_freeboard'),
    path('free_board/<int:pk>/', views.freeboard_detail, name='freeboard_detail'),
    path('freeboard/edit/<int:pk>/', views.edit_freeboard, name='edit_freeboard'),
    path('delete/<int:post_id>/', views.delete_freeboard, name='delete_freeboard'),
    path('team_info', views.team_info, name='team_info'),
    path('load_prediction/', views.load_prediction, name='load_prediction'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('copyright', views.copyright, name='copyright'),
    path("chat/", views.chat, name='chat'),
    path("chat/clear_logs/", views.chat_clear_logs, name='chat_clear_logs'),
    path('auto_admin_login', views.auto_admin_login, name='auto_admin_login'),
    path('get_scenarios/<str:scenario_type>/', views.get_scenarios, name='get_scenarios'),
    path('freeboard/<int:pk>/download/', views.generate_presigned_url, name='generate_presigned_url'),
    path('board/<int:pk>/download/', views.board_generate_presigned_url, name='board_generate_presigned_url'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("control/", include('control.urls')),
    path('adminpanel/', include('adminpanel.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

adminpanel/models.py
from django.db import models

adminpanel/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import json
import csv
import io
import boto3
from django.conf import settings
from collections import Counter
from django.db.models import Q
from django.utils.timezone import localtime
import time 
import hmac
import hashlib
import uuid
import requests
import os
import datetime
from datetime import datetime, timedelta
from datetime import timezone as dt_timezone  
from django.utils import timezone
from .utils import mask_user_data
from urllib.parse import quote

from main.views import add_qa_to_database
from main.forms import *
from main.models import *

def get_signature(key, msg):
    return hmac.new(key.encode(), msg.encode(), hashlib.sha256).hexdigest()

def unique_id():
    return str(uuid.uuid1().hex)

def get_iso_datetime():
    utc_offset_sec = time.altzone if time.localtime().tm_isdst else time.timezone
    utc_offset = timedelta(seconds=-utc_offset_sec)
    return datetime.now().replace(tzinfo=dt_timezone(offset=utc_offset)).isoformat()

def get_headers(apiKey, apiSecret):
    date = get_iso_datetime()
    salt = unique_id()
    data = date + salt
    signature = get_signature(apiSecret, data)
    headers = {
        'Authorization': f'HMAC-SHA256 ApiKey={apiKey}, Date={date}, salt={salt}, signature={signature}',
        'Content-Type': 'application/json'
    }
    return headers

def format_date(date_string):
    if date_string is None:
        return None
    date_obj = datetime.strptime(date_string, '%Y-%m-%dT%H:%M:%S.%fZ').replace(tzinfo=dt_timezone.utc)
    kst = dt_timezone(timedelta(hours=9))
    local_date_obj = date_obj.astimezone(kst)
    return local_date_obj.strftime('%Y-%m-%d %H:%M:%S')

def fetch_message_details(message_code):
    MESSAGE_API_KEY = os.getenv('MESSAGE_API_KEY')
    MESSAGE_API_SECRET = os.getenv('MESSAGE_API_SECRET')

    url = f"http://api.coolsms.co.kr/messages/v4/list?criteria=messageId&value={message_code}&cond=eq"
    headers = get_headers(MESSAGE_API_KEY, MESSAGE_API_SECRET)

    response = requests.get(url, headers=headers)

    response_json = response.json()
    if 'messageList' in response_json and response_json['messageList']:
        message_list = response_json.get('messageList', {})
        extracted_messages = []
        for message_id, message_data in message_list.items():
            text = message_data.get('text')
            from_number = message_data.get('from')
            deliver_date = message_data.get('dateReceived')
            if text and deliver_date:
                extracted_messages.append({
                    'text': text,
                    'from': from_number,
                    'deliver_date': format_date(deliver_date)
                })
            return extracted_messages

    return None

@login_required
def admin_home(request):

    beaches = Beach.objects.all()
    beach_count = Beach.objects.count()
    user_count = User.objects.count()
    board_count = Event_board.objects.count()
    notice_board_count = Notice_board.objects.count()
    
    last_logins = User.objects.values_list('last_login', flat=True)

    login_count = Counter()

    
    for login_time in last_logins:
        local_login_time = localtime(login_time)
        if local_login_time:
            hour = local_login_time.hour
            login_count[hour] +=1
    
    hours = list(range(24))
    counts = [login_count[hour] for hour in hours]
    
    
    message_codes = Message.objects.values_list('message_code', flat=True)
    messages = []
    for message_code in message_codes:
        message_details = fetch_message_details(message_code)
        if isinstance(message_details, list):
            messages.extend(message_details)
        else:
            messages.append(message_details)
    
    sorted_messages = sorted(messages, key=lambda x: x.get('deliver_date', ''), reverse=True)
    return render(request, 'adminpanel/admin_home.html',
                  {'hours':hours, 'counts':counts, 'beaches': beaches, 
                   'user_count':user_count, 'beach_count':beach_count,
                   'board_count':board_count, 'notice_board_count':notice_board_count,
                   'messages':sorted_messages
                   })


@login_required
def senario(request):
    scenario_code = request.GET.get('scenario_code', '')

    if scenario_code:
        scenario_list = Scenario.objects.filter(scenario_code=scenario_code)
    else:
        scenario_list = Scenario.objects.all()

    paginator = Paginator(scenario_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    
    return render(request, 'adminpanel/senario.html', {'page_obj': page_obj, 'scenario_code': scenario_code})



# CSV 업로드 핸들러
@login_required
def csv_upload(request):
    if request.method == 'POST':
        csv_file = request.FILES['csv_file']
        if not csv_file.name.endswith('.csv'):
            return render(request, 'csv_upload.html', {'error': 'CSV 파일이 아닙니다.'})
        
        file_data = csv_file.read().decode('utf-8-sig')
        csv_reader = csv.reader(io.StringIO(file_data))
        next(csv_reader)  # 첫 번째 행(헤더) 건너뛰기
        
        # 현재 마지막 ID 저장
        last_id = Scenario.objects.latest('scenario_id').scenario_id if Scenario.objects.exists() else 0
        
        for row in csv_reader:
            if len(row) < 6:
                continue
            
            try:
                scenario_time = datetime.strptime(row[2], '%H:%M')
            except ValueError:
                continue
            
            Scenario.objects.create(
                scenario_code=row[1],
                scenario_time=scenario_time,
                scenario_situation=row[3],
                scenario_process=row[4],
                scenario_goals=row[5],
                scenario_qa=row[6]
            )
        
        add_qa_to_database(last_id)
        return redirect('adminpanel:senario')
    
    return render(request, 'adminpanel/csv_upload.html')

@login_required
def delete_senario(request):
    try:
        data = json.loads(request.body)
        ids_to_delete = data['ids']
        Scenario.objects.filter(scenario_id__in=ids_to_delete).delete()
        return JsonResponse({"status": "success"}, status=200)
    except Exception as e:
        return JsonResponse({"status": "error", "message": str(e)}, status=400)

# 자유게시판
@login_required
def board_manage(request):    
    beach_no = request.GET.get('beach_no')
    
    if beach_no == 'common':
        posts = Event_board.objects.filter(beach_no__isnull=True).order_by('-event_wdate')
    elif beach_no:
        posts = Event_board.objects.filter(beach_no=beach_no).order_by('-event_wdate')
    else:
        posts = Event_board.objects.all().order_by('-event_wdate')
    
    # 검색 기능
    search_keyword = request.GET.get('q', '')
    search_type  = request.GET.get('type', '')
    
    if search_keyword:
        if len(search_keyword) > 1:
            if search_type == 'all': 
                posts = posts.filter(Q (event_title__icontains=search_keyword) 
                                              | Q (event_contents__icontains=search_keyword) 
                                              | Q (user_no__user_name__icontains=search_keyword) )
            elif search_type =='title':
                posts = posts.filter(event_title__icontains=search_keyword)
                
            elif search_type == 'content' :
                posts = posts.filter(event_contents__icontains=search_keyword)
                
            elif search_type == 'writer' :
                posts = posts.filter(user_no__user_name__icontains=search_keyword)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요!')
    
    # 페이징 처리
    paginator = Paginator(posts, 10) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    beaches = Beach.objects.all()
    
    return render(request, 'adminpanel/board_manage.html', {'posts': posts, 'page_obj': page_obj, 'beaches' : beaches})

@require_POST
@login_required
def delete_boards(request):
    try:
        data = json.loads(request.body)
        ids_to_delete = data['ids']
        Event_board.objects.filter(event_id__in=ids_to_delete).delete()
        return JsonResponse({"status": "success"}, status=200)
    except Exception as e:
        return JsonResponse({"status": "error", "message": str(e)}, status=400)
    
@login_required
def user_list_view(request):
    users = User.objects.all().order_by('user_no') 
    masked_users = [mask_user_data(user) for user in users]
    paginator = Paginator(masked_users, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, 'adminpanel/user_list.html', context)

@login_required
def user_detail(request, user_no):
    user_info = User.objects.get(user_no=user_no)
    return render(request, 'adminpanel/user_detail.html', {'user_info': user_info})

@csrf_exempt
@login_required
def delete_users(request):
    if request.method == 'POST':
        user_ids = request.POST.getlist('ids[]')
        if user_ids:
            User.objects.filter(user_no__in=user_ids).delete()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'no ids provided'}, status=400)
    return JsonResponse({'status': 'invalid request'}, status=400)

# 공지사항
@login_required
def notice_manage(request):
    beach_no = request.GET.get('beach_no')

    
    if beach_no == 'common':
        posts = Notice_board.objects.filter(beach_no__isnull=True).order_by('-notice_wdate')

adminpanel/templates/adminpanel/board_detail.html
{% extends "base/admin_base.html" %}
{% block title %}{{ post.event_title }}{% endblock %}

{% block sidebar_brand %}
<a class="navbar-brand mx-4 mb-3">
    <h3 class="text-primary">자유게시판 관리</h3>
</a>
{% endblock %}

{% block user_info %}
<h6 class="mb-0">27조</h6>
<span>admin</span>
{% endblock %}

{% block content %}
        <!-- Event Detail Start -->
        <div class="container-fluid pt-4 px-4" id="contentbox-1">
            <div class="row g-4" id="contentbox-2">
                <div class="col-lg-12">
                    <div class="bg-light text-center rounded p-4" id="contentbox-3">
                        <h4 class="mb-3">{{ post.event_title }}</h4> 
                        <div class="d-flex justify-content-between">
                            <span>작성자: {{ post.user_no.user_name }}</span>
                            <span>구분: {% if post.beach_no %}{{ post.beach_no.beach_name }}{% else %}공통{% endif %}</span>
                            <span>작성일시: {{ post.event_wdate|date:"Y-m-d H:i" }}</span>
                            <span>조회수: {{ post.event_views }}</span>
                        </div>
                        <hr>
                        <div class="text-start">
                            <p style="white-space: pre-line;">{{ post.event_contents }}</p>
                            {% if post.event_img and post.event_img != "None" %}
                            <div>
                                <img src="{{ post.event_img }}" alt="첨부 이미지" style="max-width: 100%; height: auto; max-height: 400px;">
                                <div>
                                    <a href="#" id="downImageButton" >{{event_img_filename}}</a>
                                </div>
                            </div>
                        {% endif %}
                        {% if event_files %}
                        <div>
                            <ul style="list-style-type: none; padding: 0;">
                                {% for filename, file_url in event_files %}
                                <li>
                                    <a href="#" class="downloadFileButton" data-file-url="{{ file_url }}">{{ filename }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                        </div>
                        <hr>
                        <div class="text-end">
                            <a href="{% url 'adminpanel:board_manage' %}" class="btn btn-primary">목록으로</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Event Detail End -->


<script>
    document.addEventListener('DOMContentLoaded', function()  {

        var downloadImageButton = document.getElementById('downloadImageButton');
        var downloadFileButtons = document.querySelectorAll('.downloadFileButton');
    
    
        if (downloadImageButton) {
            downloadImageButton.addEventListener('click', function() {
                fetch("{% url 'board_generate_presigned_url' post.pk %}")
                .then(response => response.json())
                .then(data => {
                    if (data.url) {
                        window.location.href = data.url;
                    } else {
                        alert('파일 다운로드에 실패했습니다.');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            });
        }
    
        downloadFileButtons.forEach(function(button) {
            button.addEventListener('click', function() {
                var fileUrl = this.getAttribute('data-file-url');
                window.location.href = fileUrl;
            });
        });
    
    });
</script>
{% endblock %}

adminpanel/templates/adminpanel/notice_manage.html
{% extends "base/admin_base.html" %}
{% block title %}공지사항 관리{% endblock %}

{% block sidebar_brand %}
    <a class="navbar-brand mx-4 mb-3">
        <h3 class="text-primary">공지사항 관리</h3>
    </a>
{% endblock %}

{% block content %}
            <!-- Notices Start -->
            <div class="container-fluid pt-4 px-4"id="contentbox-1">
                <div class="row g-4"id="contentbox-2">
                    <div class="col-lg-12">
                        <div class="bg-light text-center rounded p-4"id="contentbox-3">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h4 class="mb-0">공지사항</h4>
                                <div class="d-flex">
                                    <a href="{% url 'adminpanel:create_notice' %}" class="btn btn-secondary me-2">글쓰기</a> 
                                    <div class="dropdown me-2">
                                        <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                            {% if request.GET.beach_no %}
                                                {% for beach in beaches %}
                                                    {% if beach.beach_no == request.GET.beach_no %}
                                                        {{ beach.beach_name }}
                                                    {% endif %}
                                                {% endfor %}
                                                {% if request.GET.beach_no == 'common' %}
                                                    공통
                                                {% endif %}
                                            {% else %}
                                                전체
                                            {% endif %}
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"style="background-color: transparent;">
                                            <a class="dropdown-item" href="?">전체</a>
                                            <a class="dropdown-item" href="#" data-beach-no="common">공통</a>
                                            {% for beach in beaches %}
                                                <a class="dropdown-item" href="#" data-beach-no="{{ beach.beach_no }}">{{ beach.beach_name }}</a>
                                            {% endfor %}
                                            
                                        </div>
                                    </div>
                                    <button id="deleteButton" class="btn btn-primary">삭제</button> 
                                </div>
                            </div>
                            <!-- Table for Notices -->
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th scope="col" style="width: 5%;">
                                                <input type="checkbox" id="selectAll">
                                            </th>
                                            <th scope="col" style="width: 5%;">글 번호</th> 
                                            <th scope="col" style="width: 15%;">구분</th> 
                                            <th scope="col" style="width: 50%;">제목</th> 
                                            <th scope="col" style="width: 10%;">작성자</th> 
                                            <th scope="col" style="width: 20%;">등록일시</th>
                                        </tr>
                                    </thead>
                                    <tbody id="noticeTableBody">
                                        {% for post in page_obj %}
                                        <tr data-id="{{ post.notice_id }}">
                                            <td><input type="checkbox" class="selectRow"></td>
                                            <td>{{ forloop.counter0|add:page_obj.start_index}}</td>
                                            <td>
                                                {% if post.beach_no %}
                                                    {{ post.beach_no.beach_name }}
                                                {% else %}
                                                    공통
                                                {% endif %}
                                            </td>
                                            <td><a href="{% url 'adminpanel:notice_detail' post.pk %}">{{ post.notice_title }}</a></td>
                                            <td>{{ post.user_no.user_name }}</td>
                                            <td>{{ post.notice_wdate |date:"Y-m-d H:i" }}</td>                         
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="6">No posts found.</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- Pagination Controls -->
                            <div class="d-flex justify-content-center">
                                <nav>
                                    <ul class="pagination">
                                        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                                            <a class="page-link" href="?page=1&beach_no={{ request.GET.beach_no }}&type={{ request.GET.type }}&q={{ request.GET.q|urlencode }}" aria-label="First">
                                                <span aria-hidden="true">&laquo;&laquo;</span>
                                            </a>
                                        </li>
                                        {% for num in page_obj.paginator.page_range %}
                                            {% if page_obj.number == num %}
                                                <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                                        {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ num }}&beach_no={{ request.GET.beach_no }}&type={{ request.GET.type }}&q={{ request.GET.q|urlencode }}">{{ num }}</a>
                                            </li>
                                            {% endif %}
                                        {% endfor %}
                                        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&beach_no={{ request.GET.beach_no }}&type={{ request.GET.type }}&q={{ request.GET.q|urlencode }}" aria-label="Last">
                                                <span aria-hidden="true">&raquo;&raquo;</span>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- End of Pagination Controls -->
                            <!-- Search Bar -->
                            <div class="container pt-4">
                                <div class="row justify-content-center"> <!-- 중앙 정렬 -->
                                    <div class="col-lg-6">
                                        <form action="{% url 'adminpanel:notice_manage' %}" method="get" onsubmit="return validateSearchForm()">
                                            <div class="form-group">
                                                <div class="input-group mb-3">
                                                    <select class="form-select" name="type">
                                                        <option value="all" {% if request.GET.type == 'all' %}selected{% endif %}>전체</option>
                                                        <option value="title" {% if request.GET.type == 'title' %}selected{% endif %}>제목</option>
                                                        <option value="content" {% if request.GET.type == 'content' %}selected{% endif %}>내용</option>
                                                        <option value="writer" {% if request.GET.type == 'writer' %}selected{% endif %}>작성자</option>
                                                    </select>
                                                    <input class="form-control" type="search" placeholder="검색" name="q" value="{{ request.GET.q }}" aria-label="Search">
                                                    <input type="hidden" name="beach_no" value="{{ request.GET.beach_no }}">
                                                    <button class="btn btn-outline-primary" type="submit">검색</button>
                                                </div>
                                                <p id="errorMessage" style="color:red; display:none;">검색어는 2글자 이상 입력해주세요!</p>
                                            </div>
                                        </form>                                                                               
                                    </div>
                                </div>
                            </div>                         
                            <!-- End of Search Bar -->

                        </div>
                    </div>
                </div>
            </div>
            <!-- Notices End -->

{% block end-script %}
<!-- JavaScript to handle deletion -->
    <script>
        document.getElementById('selectAll').addEventListener('change', function() {
            var checkboxes = document.querySelectorAll('.selectRow');
            for (var checkbox of checkboxes) {
                checkbox.checked = this.checked;
            }
        });
        // post 삭제
        document.getElementById('deleteButton').addEventListener('click', function() {
            if(confirm('정말로 삭제하시겠습니까?')) {
                var checkboxes = document.querySelectorAll('.selectRow:checked');
                var idsToDelete = [];
                checkboxes.forEach(function(checkbox) {
                    idsToDelete.push(checkbox.closest('tr').getAttribute('data-id'));
                });
                if (idsToDelete.length > 0) {
                    fetch('{% url 'adminpanel:delete_notice_boards' %}', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify({ ids: idsToDelete })
                    })
                    .then(response => response.json())
                    .then(data => {
                        console.log(data);
                        if (data.status === "success") {
                            location.reload(); // 성공시 페이지 리로드
                        } else {
                            alert("Error: " + data.message); // 실패시 메시지 출력
                        }
                    })
                    .catch(error => console.error('Error:', error));
                }
            }
        });        
    </script>
    <script> // 구분 버튼 키 이름 변경
        document.addEventListener('DOMContentLoaded', function() {
            const dropdownItems = document.querySelectorAll('.dropdown-item');
            const dropdownButton = document.getElementById('dropdownMenuButton');
            const currentUrl = new URL(window.location);
            const currentParams = currentUrl.searchParams;
            
            dropdownItems.forEach(item => {
                item.addEventListener('click', function() {
                    currentParams.set('beach_no', this.getAttribute('data-beach-no'));
                    currentParams.set('page', '1'); // 선택 시 페이지를 리셋
                    currentUrl.search = currentParams.toString();
                    window.location.href = currentUrl.toString();
                });
            });
        
            const selectedBeachNo = currentParams.get('beach_no');
            dropdownItems.forEach(item => {
                if (item.getAttribute('data-beach-no') === selectedBeachNo) {
                    dropdownButton.textContent = item.textContent;
                }
            });
        });
    </script>

    <script>// 검색 기능 에러 알람
        function validateSearchForm() {
            var searchInput = document.querySelector('input[name="q"]');
            var errorMessage = document.getElementById('errorMessage');
            if (searchInput.value.length < 2) {
                errorMessage.style.display = 'block'; // 오류 메시지를 표시
                return false; // 폼 제출을 방지
            }
            errorMessage.style.display = 'none'; // 오류 메시지를 숨김
            return true; // 폼 제출을 계속
        }
    </script>
{% endblock %}


{% endblock %}